//
// Autogenerated based on code by L. J. Feldstein
//

#ifndef CIMPLE_ACT_IMPL_H
#define CIMPLE_ACT_IMPL_H

#include <stdio.h>
#include "cimple_controller.h"

    void ACT_0x3F408380(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408290(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AC50(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408440(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40DBD0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4081D0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407F90(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408110(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408350(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A9D0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408050(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D770(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AF40(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B4F0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B150(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B400(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C9C0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B030(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B340(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B430(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B620(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4099E0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BA30(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B0F0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409F30(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B310(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AEE0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AFD0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F406D00(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4070A0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4078B0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F406F50(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4077F0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4074A0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407250(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407160(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407700(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407220(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407310(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4073D0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407980(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F406E80(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407560(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407640(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D0F0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CC30(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CB50(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CDB0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D020(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CEA0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407BF0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BE60(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A070(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AD40(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700870(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BD40(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D1D0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CF30(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407B30(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BF20(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D3B0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F406CA0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D6B0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D4E0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4087B0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409950(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409980(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409590(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409890(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4086F0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409650(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409A40(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409EA0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A850(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AD10(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D950(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AB80(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409460(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4092B0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409070(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409370(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F4093A0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408FB0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C7B0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C960(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C870(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C3C0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BDD0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C6C0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C0F0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C480(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BFE0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40C240(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408E80(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408B50(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408C10(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409C40(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409D40(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408CD0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408DC0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409F90(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408D90(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A4C0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A0A0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A3E0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A250(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A160(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A220(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409E70(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A580(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40A310(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CF00(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BE30(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407DA0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407E60(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407D70(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F407CB0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F406FB0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F406D90(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B820(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700CD0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700540(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B5B0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700240(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700970(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B9D0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700C00(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B8E0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700150(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B680(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D740(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D710(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40E6E0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40DC90(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40DD80(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D880(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40E330(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D920(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CA80(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40D600(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AE80(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40CCC0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40AFA0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700B40(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700300(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700810(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700180(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700660(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F7003D0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700A50(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F700090(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408570(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408A20(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408870(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408930(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408960(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F408630(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40B740(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BA90(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F40BB60(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409CE0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

    void ACT_0x3F409B00(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

#endif //CIMPLE_ACT_IMPL_H