//
// Autogenerated based on code by L. J. Feldstein
//

#ifndef CIMPLE_ACT_IMPL_H
#define CIMPLE_ACT_IMPL_H

#include <stdio.h>
#include "cimple_controller.h"

void ACT_1(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_2(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_3(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_8(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_4(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_5(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_6(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_7(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

#endif //CIMPLE_ACT_IMPL_H