//
// Autogenerated based on code by L. J. Feldstein
//

#ifndef CIMPLE_ACT_IMPL_H
#define CIMPLE_ACT_IMPL_H

#include <stdio.h>
#include "cimple_controller.h"

void ACT_m1(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_m0(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_m2(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

void ACT_m3(current_state * now, discrete_dynamics * d_dyn, system_dynamics * s_dyn, cost_function * f_cost);

#endif //CIMPLE_ACT_IMPL_H